### ISSUE TITLE
[4pdvGPU ERROR (pid:167 thread=140191321859904 multiprocess_memory_limit.c:455)]: Failed to lock shrreg: 4

### ISSUE THREAD

**Issue by Chenyangzh** [4paradigm/k8s-vgpu-scheduler#26]
hi，

容器内分配了三张gpu，启动6个进程服务，启动正常，运行一段时间后报错如下

[4pdvGPU ERROR (pid:167 thread=140191321859904 multiprocess_memory_limit.c:455)]: Failed to lock shrreg: 4
python3.7: /home/limengxuan/work/libcuda_override/src/multiprocess/multiprocess_memory_limit.c:455: lock_shrreg: Assertion `0' failed.
python3.7: /home/limengxuan/work/libcuda_override/src/multiprocess/multiprocess_memory_limit.c:455: lock_shrreg: Assertion `0' failed.
[2022-06-16 18:30:58 +0800] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/opt/python37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/translation/server.py", line 40, in <module>
    initModels(device)
  File "/translation/Opus.py", line 12, in initModels
    model = OPUSModel(device, OPUS_PATH+m)
  File "/translation/OpusMT.py", line 16, in __init__
    self.model.to(self.device)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid argument
[2022-06-16 18:30:58 +0800] [168] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/python37/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/opt/python37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/translation/server.py", line 40, in <module>
    initModels(device)
  File "/translation/Opus.py", line 12, in initModels
    model = OPUSModel(device, OPUS_PATH+m)
  File "/translation/OpusMT.py", line 16, in __init__
    self.model.to(self.device)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/opt/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid argument
[2022-06-16 18:30:58 +0800] [12] [INFO] Worker exiting (pid: 12)
[2022-06-16 18:30:58 +0800] [168] [INFO] Worker exiting (pid: 168)
[2022-06-16 18:30:59 +0800] [163] [WARNING] Worker with pid 167 was terminated due to signal 6
[2022-06-16 18:30:59 +0800] [688] [INFO] Booting worker with pid: 688
[2022-06-16 18:31:00 +0800] [7] [WARNING] Worker with pid 11 was terminated due to signal 6
[2022-06-16 18:31:00 +0800] [752] [INFO] Booting worker with pid: 752
merge pid=45194merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=45194merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=45194merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pi
d=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=45194merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=49905merge pid=49905merge pid=49905merge pid=49905merge pid=49905merge pid=49905merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=59211merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=49804merge pid=45194merge pid=45194merge pid=45847merge pid=45847merge pid=45847merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47069merge pid=47069merge pid=47069merge pid=47069merge pid=47069[2022-06-16 18:31:36 +0800] [163] [INFO] Shutting down: Master
[2022-06-16 18:31:36 +0800] [163] [INFO] Reason: Worker failed to boot.
[2022-06-16 18:31:37 +0800] [7] [INFO] Shutting down: Master
[2022-06-16 18:31:37 +0800] [7] [INFO] Reason: Worker failed to boot.
[4pdvGPU ERROR (pid:460 thread=140489760016192 multiprocess_memory_limit.c:455)]: Failed to lock shrreg: 4
python3.7: /home/limengxuan/work/libcuda_override/src/multiprocess/multiprocess_memory_limit.c:455: lock_shrreg: Assertion `0' failed.
[2022-06-17 04:42:32 +0800] [454] [WARNING] Worker with pid 460 was terminated due to signal 6
[2022-06-17 04:42:32 +0800] [4395] [INFO] Booting worker with pid: 4395
merge pid=47068merge pid=59211merge pid=59211merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=47068merge pid=11907merge pid=11907merge pid=59211merge pid=59211merge pid=59211merge pid=47068merge pid=47068merge pid=47068merge pid=47068[2022-06-17 04:45:49 +0800] [454] [CRITICAL] WORKER TIMEOUT (pid:459)
[2022-06-17 04:45:54 +0800] [454] [WARNING] Worker with pid 459 was terminated due to signal 9
[2022-06-17 04:45:54 +0800] [4504] [INFO] Booting worker with pid: 4504
merge pid=11907merge pid=59211merge pid=59211merge pid=11907merge pid=11907merge pid=11907merge pid=11907merge pid=11907merge pid=19026merge pid=19026merge pid=59211merge pid=59211merge pid=59211merge pid=11907merge pid=11907merge pid=11907merge pid=11907[2022-06-17 04:49:46 +0800] [454] [CRITICAL] WORKER TIMEOUT (pid:4395)
[2022-06-17 04:49:48 +0800] [454] [WARNING] Worker with pid 4395 was terminated due to signal 9
[2022-06-17 04:49:48 +0800] [4611] [INFO] Booting worker with pid: 4611

**Comment by archlitchi** [comment]
可以告诉我一下你的cuda版本和驱动版本吗

**Comment by Chenyangzh** [comment]
> 可以告诉我一下你的cuda版本和驱动版本吗

显卡：rtx3090
驱动版本：510.68.02
容器内cuda版本：V11.1.105

**Comment by archlitchi** [comment]
这个问题可以稳定复现吗

**Comment by archlitchi** [comment]
因为我看这里（4pdvGPU ERROR (pid:460 thread=140489760016192 multiprocess_memory_limit.c:455)]: Failed to lock shrreg: 4）

错误编码是4（EINTR），好像是被人ctrl+c掉了

**Comment by Chenyangzh** [comment]
> 因为我看这里（4pdvGPU ERROR (pid:460 thread=140489760016192 multiprocess_memory_limit.c:455)]: Failed to lock shrreg: 4）
> 
> 错误编码是4（EINTR），好像是被人ctrl+c掉了

那应该是服务调用压力过大，gunicorn进程自己给干掉了。进程重启失败导致的。这个问题不能稳定复现，有的pod运行很久都没事，有的挂掉只剩下一路。

感谢您提供的信息，我这边再看看pod里面的服务访问记录吧。

另外想问下，
1. 有时候在pod里nvidia-smi会发现显存使用量会超过分配值，这个是什么原因呀。
2. 容器在本地测试显存只占1.5g，在vgpu集群里会占到2.2g多，且占用不稳定。pod配置vgpu资源时该依据什么来分配呢？

**Comment by archlitchi** [comment]
1. 这个一般我会允许pod超用分配额10%以内，如果限制太死的话，很多tensorflow任务就会跑不了。2. vgpu的话，有一些自己的管理上下文，可能会占用几百M的显存

当然这个也要看你们是不是用了虚拟显存（显存超卖）功能，如果用了的话，出现这些情况也是很正常的

**Comment by archlitchi** [comment]
有需要的话下个版本我可以加入这个功能

**Comment by Chenyangzh** [comment]
> > 1. 这个一般我会允许pod超用分配额10%以内

在日常使用时也会多分配一个余量，有这个功能更好啦，感谢解答！
